# This rule is not used by the project volcano-deviceplugin-mock itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to dpmock.volcano.sh resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: volcano-deviceplugin-mock
    app.kubernetes.io/managed-by: kustomize
  name: dpmock-noderesourceconfiguration-viewer-role
rules:
- apiGroups:
  - dpmock.volcano.sh
  resources:
  - noderesourceconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dpmock.volcano.sh
  resources:
  - noderesourceconfigurations/status
  verbs:
  - get
