---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.19.0
  name: noderesourceconfigurations.dpmock.volcano.sh
spec:
  group: dpmock.volcano.sh
  names:
    kind: NodeResourceConfiguration
    listKind: NodeResourceConfigurationList
    plural: noderesourceconfigurations
    shortNames:
    - nrcfg
    singular: noderesourceconfiguration
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: NodeResourceConfiguration is the Schema for the noderesourceconfigurations
          API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: spec defines the desired state of NodeResourceConfiguration
            properties:
              nodeSelector:
                description: |-
                  NodeSelector selects a set of nodes by using a label selector.
                  The resource configuration will only be applied to the nodes whose labels matches this selector.
                properties:
                  matchExpressions:
                    description: matchExpressions is a list of label selector requirements.
                      The requirements are ANDed.
                    items:
                      description: |-
                        A label selector requirement is a selector that contains values, a key, and an operator that
                        relates the key and values.
                      properties:
                        key:
                          description: key is the label key that the selector applies
                            to.
                          type: string
                        operator:
                          description: |-
                            operator represents a key's relationship to a set of values.
                            Valid operators are In, NotIn, Exists and DoesNotExist.
                          type: string
                        values:
                          description: |-
                            values is an array of string values. If the operator is In or NotIn,
                            the values array must be non-empty. If the operator is Exists or DoesNotExist,
                            the values array must be empty. This array is replaced during a strategic
                            merge patch.
                          items:
                            type: string
                          type: array
                          x-kubernetes-list-type: atomic
                      required:
                      - key
                      - operator
                      type: object
                    type: array
                    x-kubernetes-list-type: atomic
                  matchLabels:
                    additionalProperties:
                      type: string
                    description: |-
                      matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels
                      map is equivalent to an element of matchExpressions, whose key field is "key", the
                      operator is "In", and the values array contains only "value". The requirements are ANDed.
                    type: object
                type: object
                x-kubernetes-map-type: atomic
              resources:
                description: Resources describe the mock requirement of custom resource.
                items:
                  description: ResourceRequirement describes the details of the resource
                    requirement.
                  properties:
                    capacity:
                      anyOf:
                      - type: integer
                      - type: string
                      description: |-
                        Capacity indicates the resource capacity in a node.

                        In the case that ResourceInfo reference a ResourceReference, the default capacity can be defined by the reference.
                      pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                      x-kubernetes-int-or-string: true
                    nodePatchTemplate:
                      description: |-
                        NodePatchTemplate defines a node patch body based on Go Template rendering.
                        The context of the Go Template is set to the ResourceBasicDescription corresponding to current resource in status field.
                        For example, you can get the resolved result of the deviceID format by using ".deviceIDFormat".

                        In the case that ResourceInfo reference a ResourceReference, the default NodePatchTemplate can be defined by the reference.
                      type: string
                    nodeUndoPatch:
                      description: |-
                        NodeUndoPatch defines a node patch body to be executed when the resource is removed in the node.

                        In the case that ResourceInfo reference a ResourceReference, the default NodeUndoPatch can be defined by the reference.
                      type: string
                    resourceName:
                      description: ResourceName indicates the name of the resource.
                      type: string
                    resourceRef:
                      description: |-
                        ResourceRef describes the resource information by referencing other objects.
                        This field can only reference a NodeResource currently.
                      properties:
                        apiGroup:
                          description: APIGroup is the group for the resource being
                            referenced
                          type: string
                        kind:
                          description: Kind is the type of resource being referenced
                          type: string
                        name:
                          description: Name is the name of resource being referenced
                          type: string
                      required:
                      - apiGroup
                      - kind
                      - name
                      type: object
                  type: object
                type: array
            type: object
          status:
            description: status defines the observed state of NodeResourceConfiguration
            properties:
              numberAvailable:
                description: |-
                  NumberAvailable indicates the number of nodes that should apply the configuration and
                  have one daemon pod running and available.
                format: int32
                type: integer
              numberDesired:
                description: NumberDesired indicates the number of nodes that should
                  apply the configuration.
                format: int32
                type: integer
              numberSynchronized:
                description: NumberSynchronized indicates the number of nodes that
                  has synchronized the configuration.
                format: int32
                type: integer
              resourceDescriptions:
                description: ResourceDescriptions hold the ultimate resolved results
                  of the resource descriptions that defined in NodeResourceConfigurationSpec.
                items:
                  properties:
                    capacity:
                      anyOf:
                      - type: integer
                      - type: string
                      description: Capacity indicates the capacity of the resource.
                      pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                      x-kubernetes-int-or-string: true
                    deviceIDFormat:
                      description: DeviceIDFormat represents the ultimate format for
                        generating the deviceID serial.
                      properties:
                        delimiter:
                          description: Delimiter indicates the concatenation between
                            prefix and ordinal in the deviceID.
                          type: string
                        ordinalStart:
                          description: OrdinalStart indicates the starting number
                            of the ID serial.
                          format: int32
                          type: integer
                        prefix:
                          additionalProperties:
                            format: int32
                            type: integer
                          description: The map key means the prefix of the deviceID
                            and the map value means the amount of IDs corresponding
                            to the prefix.
                          type: object
                      type: object
                    nodePatch:
                      description: NodePatch holds the Go Template rendering result
                        of ResourceRequirement.NodePatchTemplate.
                      type: string
                    nodeUndoPatch:
                      description: NodeUndoPatch holds a node patch body to be executed
                        when the resource is removed in the node.
                      type: string
                    resourceName:
                      description: ResourceName indicates the name of the resource.
                      type: string
                  type: object
                type: array
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
