---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.19.0
  name: noderesources.dpmock.volcano.sh
spec:
  group: dpmock.volcano.sh
  names:
    kind: NodeResource
    listKind: NodeResourceList
    plural: noderesources
    shortNames:
    - nr
    singular: noderesource
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: NodeResource is the Schema for the noderesources API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: spec defines the desired state of NodeResource
            properties:
              defaultCapacity:
                anyOf:
                - type: integer
                - type: string
                description: DefaultCapacity defines the default capacity of the resource.
                pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                x-kubernetes-int-or-string: true
              defaultNodePatchTemplate:
                description: DefaultNodePatchTemplate defines a default node patch
                  body based on Go Template rendering.
                type: string
              defaultNodeUndoPatch:
                description: DefaultNodeUndoPatch defines a default node patch body
                  to be executed when the resource is removed in the node.
                type: string
              deviceIDGeneratePolicy:
                description: DeviceIDGeneratePolicy describes how to generate deviceID
                  serial.
                properties:
                  delimiter:
                    description: Delimiter defines the delimiter of the ID serial.
                    type: string
                  ordinalStart:
                    description: OrdinalStart defines the starting number of the ID
                      serial.
                    format: int32
                    type: integer
                  prefix:
                    description: Prefix defines the prefix of the deviceID serial.
                    properties:
                      parentResourceRef:
                        description: |-
                          ParentResourceRef indicates that the deviceID serial is prefixed with the deviceID list of the parent resource.
                          This field can only reference a NodeResource currently.
                        properties:
                          apiGroup:
                            description: APIGroup is the group for the resource being
                              referenced
                            type: string
                          kind:
                            description: Kind is the type of resource being referenced
                            type: string
                          name:
                            description: Name is the name of resource being referenced
                            type: string
                        required:
                        - apiGroup
                        - kind
                        - name
                        type: object
                      static:
                        description: Static indicates that the deviceID serial is
                          prefixed with the static string list.
                        items:
                          type: string
                        type: array
                    type: object
                type: object
              resourceName:
                description: ResourceName defines custom resource name.
                type: string
            type: object
          status:
            description: status defines the observed state of NodeResource
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
